const SIGN_UP = 'SIGN_UP';
const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE';
const SIGN_OUT = 'SIGN_OUT';
const SIGN_IN = 'SIGN_IN';
const GET_RESTAURANTS = 'GET_RESTAURANTS';
const GET_RESTAURANTS_SUCCESS = 'GET_RESTAURANTS_SUCCESS';
const GET_RESTAURANTS_FAILURE = 'GET_RESTAURANTS_FAILURE';
export {
  SIGN_UP,
  GET_RESTAURANTS,
  SIGN_OUT,
  SIGN_UP_FAILURE,
  SIGN_UP_SUCCESS,
  SIGN_IN,
  GET_RESTAURANTS_FAILURE,
  GET_RESTAURANTS_SUCCESS,
};
