const SIGN_UP = 'SIGN_UP';
const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE';
const SIGN_OUT = 'SIGN_OUT';
const SIGN_IN = 'SIGN_IN';
export {SIGN_UP, SIGN_OUT, SIGN_UP_FAILURE, SIGN_UP_SUCCESS, SIGN_IN};
